# Use the current GA “latest” NGINX alpine image (1.28.0 as of May 22 2025)
FROM nginx:alpine

# Copy the static files to the nginx html directory
COPY index.html /usr/share/nginx/html/index.html

# Exposes port 80 for the web server
EXPOSE 80
